<a href="https://colab.research.google.com/github/c-carrascos/math/blob/main/Practica_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3. Álgebra
* Para aprender sobre Python vea la playlist [Python para Matemáticas](https://www.youtube.com/playlist?list=PL8gpDXwO-9l4HkDJ9QhB4H-cOiT0BYGau)
* Para obtener ideas y vídeos para la resolución de la práctica vea los archivos siguientes: [Ideas](https://github.com/financieras/math/tree/main/ideas)

## Práctica 3.1
**Determinante en Excel**  

* Cree un fichero en Excel de nombre algebra.xlsm.
* La extensión **xlsm** corresponde a los archivos de Excel habilitados para macros.
* Utilice la Hoja 1 para hacer la Práctica 3.1.
* Se pide:
 1. Cree una matriz cuadrada de dimensión 5×5, formada por números aleatorios enteros entre -9 y +9.
 2. Calcule el determinante de esta matriz
 3. Cree un programa en **VBA** que busque una matriz de este tipo cuyo determinante sea cero.
 4. Copie la matriz encontrada y péguela debajo con "pegado especial valores" para que no varíe su contenido al efectuar el recálculo manual de la hoja.

## Práctica 3.2
**Matriz inversa en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 2 para hacer la Práctica 3.2.
* Se pide:
 1. Crea la matriz $A$ que es una matriz cuadrada de dimensiones 5×5 usando números aleatorios enteros entre -9 y +9, excepto cero
 2. Calcule su determinante
 3. Calcule su transpuesta usando la función ```TRANSPONER```
 4. Calcule su matriz inversa $A^{-1}$
 5. Multiplique la matriz $A$ por su inversa $A^{-1}$ y compruebe que el producto es la matriz identidad.
 $$AA^{-1}=I$$

## Práctica 3.3
**Resolución de sistemas lineales en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 3 para hacer la Práctica 3.3.
* Se pide:
 1. Cree un sistema de 5 ecuaciones con 5 incógnitas con **solución única**.
 2. Una de las ecuaciones será: $\quad x_1+2x_2-x_3+x_4-3x_5=6$
 3. Muestre las ecuaciones del sistema usando el [editor de ecuaciones](https://support.microsoft.com/es-es/office/editor-de-ecuaciones-6eac7d71-3c74-437b-80d3-c7dea24fdf3f) de Excel. $\quad Ax=b$
 4. Monte la matriz $A$ del sistema de ecuaciones y la matriz $b$ con los términos independientes. Muestre ambas matrices.
 5. Calcule la matriz inversa $A^{-1}$
 6. Resuelva el sistema lineal de ecuaciones con este método: $\quad Ax=b \quad \Longrightarrow \quad x=A^{-1}b$
 7. Compruebe si el resultado obtenido es la solución del sistema de ecuaciones. Justifique esa comprobación.

## Práctica 3.4
**Matriz inversa en Python**  

Desarrolla un código en Python que al ejecutarse consiga los siguientes apartados.  
1. Crea una matriz cuadrada de dimensiones 3×3 usando números aleatorios enteros entre -9 y +9, excepto cero
2. Buscar un caso donde el determinante sea igual a 1
3. Si el determinante es 1 imprime la matriz y su determinante
4. Calcula e imprime su transpuesta
5. Calcula e imprime su matriz inversa
6. Multiplica la matriz creada por su inversa y comprueba que el producto es la matriz identidad.
7. Calcula cuantos segundos ha tardado en realizarse el proceso.

In [ ]:
import numpy as np
from random import randint, choice
from time import process_time

n = 3   

while True:
    m = np.random.randint(1,9, size=(n, n))* choice ([1,-1])   # aleatorios enteros entre -9 y +9, sin incluir el 0
    determ = np.linalg.det(m)
    if determ == 1:
        print(m)
        break

print(f"El determinante de la matriz es {determ}")


#transpuesta de la matriz:
print("\nTasnpuesta:")
print(np.transpose(m))


#inversa de la matriz:
print("\nInversa:")
minv = np.linalg.inv(m)
print(minv)


#producto de matriz por su inversa
print("Matriz Identidad:")
identidad = np.dot(m, minv)   # multiplicación de matrices
print(identidad)



#tiempo que ha tardado el proceso
t1 = process_time()

for i in range(10_000_000):
    cuadrado = i**2

t2 = process_time()
print(f"El proceso ha tardado {t2-t1} segundos.")

[[3 5 6]
 [4 7 1]
 [4 7 2]]
El determinante de la matriz es 1.0

Tasnpuesta:
[[3 4 4]
 [5 7 7]
 [6 1 2]]

Inversa:
[[  7.  32. -37.]
 [ -4. -18.  21.]
 [  0.  -1.   1.]]
Matriz Identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
El proceso ha tardado 3.408742321999995 segundos.


## Práctica 3.5
**Resolución de sistemas lineales en Python**  

1. Cree un sistema de 4 ecuaciones con 4 incógnitas con **solución única**.
2. La solución del sistema es: $\; \begin{pmatrix}x_1, x_2, x_3, x_4\end{pmatrix} = \begin{pmatrix} 3, 4, 5, 2\end{pmatrix}$  
3. Una de las ecuaciones del sistema es: $\enspace x_1+3x_2-x_3-2x_4=6$  
4. El vector $b$ de términos independientes es: $\enspace b=\begin{pmatrix}6, 3, 5, 7\end{pmatrix}$  
5. Usando números aleatorios elija los coeficientes que faltan de la matriz $A$ del sistema de ecuaciones.
  - Los coeficientes deben ser números enteros entre -5 y +5, excluido el cero.
  - Imprima la matriz $A$.  
6. Calcule e imprima el determinante de $A$.
7. Calcule e imprima la matriz inversa $A^{-1}$  
8. Resuelva el sistema lineal de ecuaciones con este método: $$Ax=b \quad \Longrightarrow \quad x=A^{-1}b$$
9. Compruebe que el resultado obtenido es la solución del sistema de ecuaciones.  
10. Resuelva nuevamente el sistema de ecuaciones usando ```np.linalg.solve```.

In [1]:
import numpy as np
np.random.choice([0,1,2,3,4,5,6,7,8,9], 3)


list(range(-9,0)) + list(range(1,10))
     
v = np.array([3,4,5,2])   # vector conocido, es la solución de sistema lineal

def busca(b):
    while True:
        w = np.random.choice(list(range(-5,0)) + list(range(1,6)), 4)
        if np.matmul(v, w) == b:   # el producto de los dos vectores debe ser igual al número b
            break
    return w

b =  5; print(f"{busca(b)} x {v} = {b}")
b = -3; print(f"{busca(b)} x {v} = {b}")
b = -1; print(f"{busca(b)} x {v} = {b}")
b = -2; print(f"{busca(b)} x {v} = {b}")

# Multiplicando a mano el primer vector sería un vector fila y
# el segundo un vector columna
# Al usar NumPy no nos preocupamos de la congruendia de vectores

[-4 -1  3  3] x [3 4 5 2] = 5
[ 4 -3 -1  1] x [3 4 5 2] = -3
[-1  5 -4  1] x [3 4 5 2] = -1
[-2  5 -2 -3] x [3 4 5 2] = -2
[[-4, -2, 4, 2], [-5, 2, 4, -5], [-5, 5, -3, 4], [2, 2, -1, -5]]



array([[-4, -2,  4,  2],
       [-5,  2,  4, -5],
       [-5,  5, -3,  4],
       [ 2,  2, -1, -5]])

In [11]:
import numpy as np

#matriz A
print("matriz A:")
f1 = [-4, -2, 4,  2]
f2 = [-5,  2,  4, -5]
f3 = [-5, 5, -3,  4]
f4 = [2,  2, -1, -5]
matriz = [f1, f2, f3, f4]
print(matriz)
print()

# m es un ndarray (n dimensional array)
m = np.array(matriz)
m

#determinante de A
print("Determinante de A:")
print(np.linalg.det(m))

#matriz inversa de A
print("Inversa de A")
print(a_inv)

matriz A:
[[-4, -2, 4, 2], [-5, 2, 4, -5], [-5, 5, -3, 4], [2, 2, -1, -5]]

Determinante de A:
42.0000000000001
Inversa de A
[[ 0.33333333 -0.33333333  0.33333333]
 [-0.55555556  1.55555556 -0.88888889]
 [-0.11111111  1.11111111 -0.77777778]]


In [6]:
#resolucion del sistema mediante la inversa

import numpy as np
a = np.array([[2,-1,2], [3,2,-1], [4,3,-3]])
b = np.array([6,4,1])
a_inv = np.linalg.inv(a)
np.dot(a_inv, b)

     

array([1., 2., 3.])

In [12]:
#resolucion del sistema método solve
import numpy as np
a = np.array([[2,-1,2], [3,2,-1], [4,3,-3]])
b = np.array([6,4,1])
solucion = np.linalg.solve(a,b)
solucion
     

array([1., 2., 3.])

## Práctica 3.6
**Resolución de sistemas lineales con Octave**  

1. Tome el mismo sistema 4x4 con solución única del ejercicio anterior.
2. Muestra el sistema usando $\LaTeX$
3. Resuélvelo con Octave por dos métodos
4. ¿Ambos métodos dan el mismo resultado?

$\quad2x - 4y + 5z - t = 5$

$\quad3x - 4y + 4z - 2t = 1$

$\quad-x + 5y - 5z + t = -2$

$\quad4x - 3y - 3z + 2t = -3$

In [16]:
#metodo 1
%%writefile primero.m
A = [2 -4 5 -1; 3 -4 4 -2; -1 5 -5 1; 4 -3 -3 2]
b = [5; -1; -2; -3]
x= inv(A)*b
% solución 1, rats expresa los número como fracciones o enteros
s1 =rats(x)


Overwriting primero.m


In [17]:
!octave primero.m


octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
A =

   2  -4   5  -1
   3  -4   4  -2
  -1   5  -5   1
   4  -3  -3   2

b =

   5
  -1
  -2
  -3

x =

   1.0000
   2.0000
   3.0000
   4.0000

s1 =

          1
          2
          3
          4



In [18]:
#metodo 2
%%writefile segundo.m
G = [2 -4 5 -1 5; 3 -4 4 -2 -1; -1 5 -5 1 -2; 4 -3 -3 2 -3]
escalonada = rref(G)
% solución 2
s2 = rats(escalonada)
     

Writing segundo.m


In [19]:
!octave segundo.m
     

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
G =

   2  -4   5  -1   5
   3  -4   4  -2  -1
  -1   5  -5   1  -2
   4  -3  -3   2  -3

escalonada =

   1.00000   0.00000   0.00000   0.00000   1.00000
   0.00000   1.00000   0.00000   0.00000   2.00000
   0.00000   0.00000   1.00000   0.00000   3.00000
   0.00000   0.00000   0.00000   1.00000   4.00000

s2 =

          1          0          0          0          1
          0          1          0          0          2
          0          0          1          0          3
          0          0          0          1          4



## Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

In [3]:
import numpy as np
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
P_inv = np.linalg.inv(P)
print("\nD:\n", D)
print("\nP:\n", P)
print("\ninversa de P:\n", P_inv)

d:  [-2.  3. -6.  3.]

D:
 [[-2.  0.  0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0. -6.  0.]
 [ 0.  0.  0.  3.]]

P:
 [[-0.89442719 -0.31622777  0.          0.        ]
 [-0.4472136  -0.9486833   0.          0.        ]
 [ 0.          0.         -0.9701425   0.4472136 ]
 [ 0.          0.         -0.24253563 -0.89442719]]

inversa de P:
 [[-1.34164079  0.4472136  -0.         -0.        ]
 [ 0.63245553 -1.26491106 -0.         -0.        ]
 [-0.         -0.         -0.91624569 -0.45812285]
 [-0.         -0.          0.248452   -0.99380799]]


In [7]:
#compruebo igualdad

#calculo Acubo:
import numpy as np
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
print(A@A@A)

#caalculo P*dcubo*inversaP
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)
Dcubo = D @ D @ D
print("\nDcubo:\n", Dcubo)
print("\nSolución:\n", P @ Dcubo @ np.linalg.inv(P))
print("\nSi, se cumple la igualdad")

[[ -15   14    0    0]
 [ -21   34    0    0]
 [   0    0 -189 -108]
 [   0    0  -54    0]]
d:  [-2.  3. -6.  3.]

D:
 [[-2.  0.  0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0. -6.  0.]
 [ 0.  0.  0.  3.]]

P:
 [[-0.89442719 -0.31622777  0.          0.        ]
 [-0.4472136  -0.9486833   0.          0.        ]
 [ 0.          0.         -0.9701425   0.4472136 ]
 [ 0.          0.         -0.24253563 -0.89442719]]

Dcubo:
 [[  -8.    0.    0.    0.]
 [   0.   27.    0.    0.]
 [   0.    0. -216.    0.]
 [   0.    0.    0.   27.]]

Solución:
 [[-1.50000000e+01  1.40000000e+01  0.00000000e+00  0.00000000e+00]
 [-2.10000000e+01  3.40000000e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.89000000e+02 -1.08000000e+02]
 [ 0.00000000e+00  0.00000000e+00 -5.40000000e+01 -2.74319149e-15]]

Si, se cumple la igualdad


## Práctica 3.8
**Diagonalización con Octave**

Resuelva el ejercicio anterior, pero en esta ocasión utilizando Octave.

In [20]:

%%writefile diagonaliza.m
A = [-3,2,0,0; -3,4,0,0; 0,0,-5,-4; 0,0,-2,2]
[P,D]=eig(A)
Dcubo = D^3
Acubo = A^3
PxDcuboXPinv = P*Dcubo*P^-1

Writing diagonaliza.m


In [21]:
!octave diagonaliza.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
A =

  -3   2   0   0
  -3   4   0   0
   0   0  -5  -4
   0   0  -2   2

P =

  -0.89443  -0.31623   0.00000   0.00000
  -0.44721  -0.94868   0.00000   0.00000
   0.00000   0.00000  -0.97014   0.44721
   0.00000   0.00000  -0.24254  -0.89443

D =

Diagonal Matrix

  -2   0   0   0
   0   3   0   0
   0   0  -6   0
   0   0   0   3

Dcubo =

Diagonal Matrix

    -8     0     0     0
     0    27     0     0
     0     0  -216     0
     0     0     0    27

Acubo =

   -15    14     0     0
   -21    34     0     0
     0     0  -189  -108
     0     0   -54     0

PxDcuboXPinv =

   -15.00000    14.00000     0.00000     0.00000
   -21.00000    34.00000     0.00000     0.00000
     0.00000     0.00000  -189.00000  -108.00000
     0.00000     0.00000   -54.00000    -0.00000



## Práctica 3.9
**Libertad para elegir el lugar de trabajo**  
Resolver con **Octave**.

Una empresa de 1.000 empleados permite que sus trabajadores cada día acudan a trabajar a la oficina o que realicen su trabajo desde su casa. Inicialmente el 90% de la plantilla trabajaba en la oficina y solo el 10% lo hacían en casa. Se ha observado que los que un día trabajan en casa tienen una probabilidad del 70% de realizarlo también desde casa al día siguiente, pero que en el restante 30% de los casos acuden a la oficina al día siguiente. Por el contrario, se ha observado que los que un día trabajaron en la oficina al día siguiente vuelven
a la oficina en el 60% de los casos y en el 40% restante van a su casa al día siguiente.
* Determinar qué número de empleados se quedan en casa transcurridos dos días.
* ¿Y a largo plazo cuantos se quedan en casa?

In [29]:

!apt install octave
!apt update

Reading package lists... Done
Building dependency tree       
Reading state information... Done
octave is already the newest version (4.2.2-1ubuntu1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:9 http://p

In [34]:

%%writefile proceso.m
empleados = 1000
% state vector
inicial = [.9; .1]
% transition probability matrix
A = [.6, .3; .4, .7]
[P,D]=eig(A)
Dcuadrado = D^2
Acuadrado = A^2
PxDcuadradoXPinv = P*Dcuadrado*P^-1
dia2 = Acuadrado * inicial
disp("Nº de empleados que se quedan en casa el segundo día: "), disp(dia2(2)*empleados)
D10 = D^10
A10 = P*D10*P^-1
dia10 = A10*inicial
disp("Nº de empleados que se quedan en casa a largo plazo son: "), disp(dia10(2)*empleados)

Overwriting proceso.m


In [35]:
!octave proceso.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
empleados =  1000
inicial =

   0.90000
   0.10000

A =

   0.60000   0.30000
   0.40000   0.70000

P =

  -0.70711  -0.60000
   0.70711  -0.80000

D =

Diagonal Matrix

   0.30000         0
         0   1.00000

Dcuadrado =

Diagonal Matrix

   0.090000          0
          0   1.000000

Acuadrado =

   0.48000   0.39000
   0.52000   0.61000

PxDcuadradoXPinv =

   0.48000   0.39000
   0.52000   0.61000

dia2 =

   0.47100
   0.52900

Nº de empleados que se quedan en casa el segundo día: 
 529
D10 =

Diagonal Matrix

   5.9049e-06            0
            0   1.0000e+00

A10 =

   0.42857   0.42857
   0.57143   0.57143

dia10 =

   0.42857
   0.57143

Nº de empleados que se quedan en casa a largo plazo son: 
 571.43


## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?

* Ventas = 100.000
* Vector de estado inicial:

$$X_0=\left(
\begin{array}{rrrr}
 0.75  \\
  0.25
\end{array}
\right)$$

* Matriz de transición:

$$A=\left(
\begin{array}{rrrr}
 0.80 & 0.40 \\
  0.20 & 0.60 
\end{array}
\right)$$

* Estado a los tres años:
$X_3$ = $$\left(
\begin{array}{rrrr}
 0.672 \\
  0.328 
\end{array}
\right)$$

* Estado a los veinte años:
$X_20$ = $$\left(
\begin{array}{rrrr}
 2/3 \\
  1/3 
\end{array}
\right)$$


\

In [36]:
import numpy as np

X0 = np.array([.75, .25])
A = np.array([[.8, .4], [.2 ,.6]])
X3 = A@A@A@X0
print("Situación a los tres años:", X3)

d,P = np.linalg.eig(A)
D = np.diag(d)
Pinv = np.linalg.inv(P)
A10 = P@(D**10)@Pinv
X10 = A10@X0
print("Situación a los diez años:", X10)
print("Situación a los veinte años:", P@(D**20)@Pinv@X0)
     

Situación a los tres años: [0.672 0.328]
Situación a los diez años: [0.6666754 0.3333246]
Situación a los veinte años: [0.66666667 0.33333333]


In [37]:
# A cubo
A@A@A
     

array([[0.688, 0.624],
       [0.312, 0.376]])

In [38]:
# comprobación de que esta expresión es igual a A cubo
P@(D**3)@Pinv
     

array([[0.688, 0.624],
       [0.312, 0.376]])

In [39]:
A@A@A@A@A@A@A@A@A@A

array([[0.66670162, 0.66659676],
       [0.33329838, 0.33340324]])

In [40]:
P@(D**10)@Pinv

array([[0.66670162, 0.66659676],
       [0.33329838, 0.33340324]])

In [41]:
np.round(A@A@A@A@A@A@A@A@A@A, 12) == np.round(P@(D**10)@Pinv, 12)

array([[ True,  True],
       [ True,  True]])